TONE_CHOICES = (
    (None, "---------"),
    ("<o> --> <a>-Wechsel", "<o> --> <a>-Wechsel"),
    ("Ablaut", "Ablaut"),
    ("Ahd. Diphtongierung", "Ahd. Diphtongierung"),
    ("Ahd. Monopthongierung", "Ahd. Monopthongierung"),
    ("Alternanz <iu> --> <ie>", "Alternanz <iu> --> <ie>"),
    ("Analogischer Umlaut", "Analogischer Umlaut"),
    ("/â/-/ô/-Zusammenfall in /ô/", "/â/-/ô/-Zusammenfall in /ô/"),
    ("a-Umlaut", "a-Umlaut"),
    ("Auslautgesetz", "Auslautgesetz"),
    ("Auslautverhärtung", "Auslautverhärtung"),
    ("Degeminierung", "Degeminierung"),
    ("Dehnung", "Dehnung"),
    ("Dentalberührung", "Dentalberührung"),
    ("Diphthongwandel", "Diphthongwandel"),
    ("Dissimilation", "Dissimilation"),
    ("Distribution", "Distribution"),
    ("/ə⁠/-/a/-Zusammenfall in /a/", "/ə⁠/-/a/-Zusammenfall in /a/"),
    ("ê -â-Wandel", "ê -â-Wandel"),
    ("Einfügung des Dehnungs-h", "Einfügung des Dehnungs-h"),
    ("Ellision", "Ellision"),
    ("Entrundung (Delabialisierung)", "Entrundung (Delabialisierung)"),
    ("Epenthese", "Epenthese"),
    ("Epithese", "Epithese"),
    ("Ersatzdehnung", "Ersatzdehnung"),
    ("Erste germanische Lautverschiebung", "Erste germanische Lautverschiebung"),
    ("Gemination", "Gemination"),
    ("Gotische Vokalbrechung", "Gotische Vokalbrechung"),
    ("Grammatischer Wechsel", "Grammatischer Wechsel"),
    ("Haplologie", "Haplologie"),
    ("Hebung", "Hebung"),
    ("Kontaktassimilation", "Kontaktassimilation"),
    ("Kontraktion", "Kontraktion"),
    ("Kürzung", "Kürzung"),
    ("Lenisierung", "Lenisierung"),
    ("Metathese", "Metathese"),
    ("Monophonematisierung", "Monophonematisierung"),
    ("Nebensilbenabschwächung", "Nebensilbenabschwächung"),
    ("Nhd. Diphthongierung", "Nhd. Diphthongierung"),
    ("Nhd. Diphthongwandel", "Nhd. Diphthongwandel"),
    ("Nhd. Monophthongierung", "Nhd. Monophthongierung"),
    ("Palatisierung", "Palatisierung"),
    ("Primärumlaut", "Primärumlaut"),
    ("Progressive Assimilation", "Progressive Assimilation"),
    ("Prothese", "Prothese"),
    ("Regressive Assimiliation", "Regressive Assimiliation"),
    ("Restumlaut", "Restumlaut"),
    ("Rhotazismus", "Rhotazismus"),
    ("Rücknahme der Auslautverhärtung in Schreibung", "Rücknahme der Auslautverhärtung in Schreibung"),
    ("Rundung (Labialisierung)", "Rundung (Labialisierung)"),
    ("Sekundärumlaut", "Sekundärumlaut"),
    ("Senkung von <ü> und <u> vor Nasal", "Senkung von <ü> und <u> vor Nasal"),
    ("Senkung", "Senkung"),
    ("Sprossvokal-Einfügung", "Sprossvokal-Einfügung"),
    ("Übernahme der ahd. Akk.-Endung /a/ als ahd. Nom.-Endung", "Übernahme der ahd. Akk.-Endung /a/ als ahd. Nom.-Endung"),
    ("Verschärfung", "Verschärfung"),
    ("Verschiebung des /k/ zu /hh/", "Verschiebung des /k/ zu /hh/"),
    ("Vokalschwund: Apokope", "Vokalschwund: Apokope"),
    ("Vokalschwund: Prokope", "Vokalschwund: Prokope"),
    ("Vokalschwund: Synkope", "Vokalschwund: Synkope"),
    ("Wechsel der Halbvokal-Realisierung", "Wechsel der Halbvokal-Realisierung"),
    ("Wechsel der sonantischen Liquide", "Wechsel der sonantischen Liquide"),
    ("Wechsel der sonantischen Nasale", "Wechsel der sonantischen Nasale"),
    ("Zerdehnung", "Zerdehnung"),
    ("Zweite hochdeutsche Lautverschiebung", "Zweite hochdeutsche Lautverschiebung")
)
MEANING_CHOICES = (
    (None, "---------"),
    ("Bedeutungsverengung", "Bedeutungsverengung"),
    ("Bedeutungserweiterung", "Bedeutungserweiterung"),
    ("Bedeutungswandel", "Bedeutungswandel"),
    ("Meliorisierung", "Meliorisierung"),
    ("Pejorisierung", "Pejorisierung"),
)

YES_NO_CHOICES = (
    (None, "---------"),
    ("Ja", "Ja"),
    ("Nein", "Nein"),
)
