TONE_CHOICES = (
    (None, "---------"),
    ("<o> --> <a>-Wechsel", "<o> --> <a>-Wechsel"),
    ("Ablaut", "Ablaut"),
    ("Ahd. Diphtongierung", "Ahd. Diphtongierung"),
    ("Ahd. Monopthongierung", "Ahd. Monopthongierung"),
    ("Alternanz <iu> --> <ie>", "Alternanz <iu> --> <ie>"),
    ("Auslautverhärtung", "Auslautverhärtung"),
    ("Dehnung", "Dehnung"),
    ("Dentalberührung", "Dentalberührung"),
    ("Dissimilation", "Dissimilation"),
    ("Ellision", "Ellision"),
    ("Entrundung (Delabialisierung)", "Entrundung (Delabialisierung)"),
    ("Epenthese", "Epenthese"),
    ("Epithese", "Epithese"),
    ("Ersatzdehnung", "Ersatzdehnung"),
    ("Erste germanische Lautverschiebung", "Erste germanische Lautverschiebung"),
    ("Gemination", "Gemination"),
    ("Grammatischer Wechsel", "Grammatischer Wechsel"),
    ("Haplologie", "Haplologie"),
    ("Hebung", "Hebung"),
    ("Kontraktion", "Kontraktion"),
    ("Kürzung", "Kürzung"),
    ("Metathese", "Metathese"),
    ("Nhd. Diphthongierung", "Nhd. Diphthongierung"),
    ("Nhd. Diphthongwandel", "Nhd. Diphthongwandel"),
    ("Nhd. Monophthongierung", "Nhd. Monophthongierung"),
    ("Primärumlaut", "Primärumlaut"),
    ("Progressive Assimilation", "Progressive Assimilation"),
    ("Prothese", "Prothese"),
    ("Regressive Assimiliation", "Regressive Assimiliation"),
    ("Restumlaut", "Restumlaut"),
    ("Rhoatzismus", "Rhoatzismus"),
    ("Rücknahme der Auslautverhärtung in Schreibung", "Rücknahme der Auslautverhärtung in Schreibung"),
    ("Rundung (Labialisierung)", "Rundung (Labialisierung)"),
    ("Sekundärumlaut", "Sekundärumlaut"),
    ("Senkung von <ü> und <u> vor Nasal", "Senkung von <ü> und <u> vor Nasal"),
    ("Senkung", "Senkung"),
    ("Vokalschwund: Apokope", "Vokalschwund: Apokope"),
    ("Vokalschwund: Prokope", "Vokalschwund: Prokope"),
    ("Vokalschwund: Synkope", "Vokalschwund: Synkope"),
    ("Zweite hochdeutsche Lautverschiebung", "Zweite hochdeutsche Lautverschiebung")
)
MEANING_CHOICES = (
    (None, "---------"),
    ("Bedeutungsverengung", "Bedeutungsverengung"),
    ("Bedeutungserweiterung", "Bedeutungserweiterung"),
    ("Bedeutungswandel", "Bedeutungswandel"),
    ("Meliorisierung", "Meliorisierung"),
    ("Pejorisierung", "Pejorisierung"),
)
