# Generated by Django 3.0.14 on 2022-11-17 17:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titel')),
                ('graphic', models.TextField(blank=True, max_length=500, null=True, verbose_name='Graphie')),
                ('lexem', models.TextField(blank=True, max_length=500, null=True, verbose_name='Lexem')),
                ('etymology', models.TextField(blank=True, max_length=500, null=True, verbose_name='Etymologie')),
                ('semantics', models.TextField(blank=True, max_length=500, null=True, verbose_name='Semantik')),
                ('tree_node', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', related_query_name='profile', to='content.TreeNode')),
            ],
            options={
                'verbose_name': 'Wort',
                'verbose_name_plural': 'Wörter',
            },
        ),
    ]
