# Generated by Django 3.0.14 on 2022-11-17 18:26

from django.db import migrations, models
import django.db.models.deletion
import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0002_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Beschreibung')),
                ('meaning_type', solid_backend.content.fields.ConcatCharField(blank=True, concat_choices=[(('Bedeutungsverengung', 'Bedeutungsverengung'), ('Bedeutungserweiterung', 'Bedeutungserweiterung'), ('Bedeutungswandel', 'Bedeutungswandel'), ('Meliorisierung', 'Meliorisierung'), ('Pejorisierung', 'Pejorisierung')), (('Bedeutungsverengung', 'Bedeutungsverengung'), ('Bedeutungserweiterung', 'Bedeutungserweiterung'), ('Bedeutungswandel', 'Bedeutungswandel'), ('Meliorisierung', 'Meliorisierung'), ('Pejorisierung', 'Pejorisierung')), (('Bedeutungsverengung', 'Bedeutungsverengung'), ('Bedeutungserweiterung', 'Bedeutungserweiterung'), ('Bedeutungswandel', 'Bedeutungswandel'), ('Meliorisierung', 'Meliorisierung'), ('Pejorisierung', 'Pejorisierung')), (('Bedeutungsverengung', 'Bedeutungsverengung'), ('Bedeutungserweiterung', 'Bedeutungserweiterung'), ('Bedeutungswandel', 'Bedeutungswandel'), ('Meliorisierung', 'Meliorisierung'), ('Pejorisierung', 'Pejorisierung')), (('Bedeutungsverengung', 'Bedeutungsverengung'), ('Bedeutungserweiterung', 'Bedeutungserweiterung'), ('Bedeutungswandel', 'Bedeutungswandel'), ('Meliorisierung', 'Meliorisierung'), ('Pejorisierung', 'Pejorisierung'))], default='', max_length=400, seperators=[', ', ' und '], verbose_name='Mhd. zu Nhd.')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meaning', to='wabe_content.Word', verbose_name='Wort')),
            ],
            options={
                'verbose_name': 'Bedeutungswandel',
                'verbose_name_plural': 'Bedeutungswandel',
            },
        ),
    ]
