# Generated by Django 3.0.14 on 2023-01-20 13:10

from django.db import migrations
import wabe_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0004_auto_20221117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Etymologie'),
        ),
        migrations.AlterField(
            model_name='word',
            name='graphic',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Graphie'),
        ),
        migrations.AlterField(
            model_name='word',
            name='lexem',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Lexem'),
        ),
        migrations.AlterField(
            model_name='word',
            name='semantics',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Semantik'),
        ),
    ]
