# Generated by Django 3.0.14 on 2023-01-20 13:38

from django.db import migrations
import wabe_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0005_auto_20230120_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='description',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='tone',
            name='description',
            field=wabe_content.models.MDTextField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
    ]
