# Generated by Django 3.2.20 on 2023-07-03 15:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('wabe_content', '0007_auto_20230625_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='tree_node',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='word_related', related_query_name='words', to='content.treenode'),
        ),
    ]
