# Generated by Django 3.2.20 on 2023-07-03 15:57

from django.db import migrations


def populate_general_information(apps, schema_editor):
    """
    Create and populate a model instance of GeneralInforamtion and link it to the
    respective plant.
    """
    Word = apps.get_model("wabe_content", "Word")
    GeneralInformation = apps.get_model("wabe_content", "GeneralInformation")

    for obj in Word.objects.all():
        GeneralInformation.objects.create(
                name=obj.name,
                graphic=obj.graphic,
                lexem=obj.lexem,
                etymology=obj.etymology,
                semantics=obj.semantics,
                word=obj
        )


def populate_word_fields(apps, schema_editor):
    """
    Populate the fields of a Plant model instance form the linked GeneralInformation
    model instance.
    """
    Word = apps.get_model("wabe_content", "Word")

    for obj in Word.objects.all():
        general_info = obj.general_information
        obj.name = general_info.name
        obj.graphic = general_info.graphic
        obj.lexem = general_info.lexem
        obj.etymology = general_info.etymology
        obj.semantics = general_info.semantics
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0009_generalinformation'),
    ]

    operations = [
        migrations.RunPython(
            populate_general_information, populate_word_fields
        )
    ]
