# Generated by Django 3.2.20 on 2023-07-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0010_migrate_word_fields_to_general_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='etymology',
        ),
        migrations.RemoveField(
            model_name='word',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='word',
            name='lexem',
        ),
        migrations.RemoveField(
            model_name='word',
            name='name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='semantics',
        ),
    ]
