# Generated by Django 3.2.20 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabe_content', '0012_auto_20250726_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='died_out',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Ja', 'Ja'), ('Nein', 'Nein')], default=None, max_length=4, null=True, verbose_name='Ausgestorben'),
        ),
    ]
